modLoader = "javafml"
loaderVersion = "[36,)"
license = "MIT"

[[mods]]
modId = "clovertrainerutils"
version = "2.0.0"
displayName = "CloverTrainerUtils"
displayURL = "https://github.com/CloverCard"
credits = "https://github.com/CloverCard"
authors = "https://github.com/CloverCard"
description = '''
Expands trainer functionality and provides better control over trainers to server owners and staff.
'''

[[dependencies.clovertrainerutils]]
modId = "forge"
mandatory = true
versionRange = "[48,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.clovertrainerutils]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.2, 1.21)"
ordering = "NONE"
side = "BOTH"


[[dependencies.clovertrainerutils]]
modId = "pixelmon"
mandatory = true
versionRange = "[9.2.6,)"
ordering = "NONE"
side = "BOTH"
