package com.clovercard.clovertrainerutils.enums;

public enum RequestTags {
    INIT_TRAINER,
    RESET_TRAINER,

    ADD_SHUFFLE,
    REMOVE_SHUFFLE,
    LIST_SHUFFLE,
    CLEAR_SHUFFLE,

    ADD_COND_DROP,
    ADD_COND_DROP_PRESET,
    REMOVE_COND_DROP,
    CLEAR_COND_DROP,
    LIST_COND_DROP,

    ADD_CHECKPOINTS,
    ADD_CHECKPOINT_BEGINNING,
    ADD_CHECKPOINT_END,
    LIST_CHECKPOINT,
    CLEAR_CHECKPOINTS,

    ADD_START_COMMAND,
    ADD_FORFEIT_COMMAND,
    ADD_PLAYER_WIN_COMMAND,
    ADD_PLAYER_LOSS_COMMAND,

    REMOVE_START_COMMAND,
    REMOVE_FORFEIT_COMMAND,
    REMOVE_PLAYER_WIN_COMMAND,
    REMOVE_PLAYER_LOSS_COMMAND,

    CLEAR_START_COMMANDS,
    CLEAR_FORFEIT_COMMANDS,
    CLEAR_PLAYER_WIN_COMMANDS,
    CLEAR_PLAYER_LOSS_COMMANDS,

    LIST_START_COMMANDS,
    LIST_FORFEIT_COMMANDS,
    LIST_PLAYER_WIN_COMMANDS,
    LIST_LOSS_COMMANDS,

    LIST_COMMANDS,
    CLEAR_COMMANDS;
}
